### ISSUE TITLE
Why should implement huge Interface to use LibSass?

### ISSUE THREAD

**Issue by dehghani-mehdi** [sass/libsass-net#62]
Hi,

In provided wiki, usage is really simple, the code snippet is as follow:

```
var sassCompiler = new SassCompiler();
var result =  sassCompiler.Compile("body { color:blue; }");
```

But in real world usage, we should implement `ISassOptions` interface in order to use this tool. is there any to avoid that?

![libsass](https://user-images.githubusercontent.com/9152330/30496692-750ec776-9a65-11e7-9bb6-3f4e2b26c656.png)

Thanks!

**Comment by darrenkopp** [comment]
You don't need to, you just need to [instantiate an object that implements that already](https://github.com/sass/libsass-net/blob/master/LibSass.NET/Compiler/Options/SassOptions.cs). It probably shouldn't be in the `.Options` namespace as that shouldn't be a namespace (likely just because VS defaults) and it isn't discoverable that way.

Anyway, the solution is to just create that object and pass it, with whatever options you need.
